### ISSUE TITLE
Description error ?

### ISSUE THREAD

**Issue by MockingMagician** [drewstephensdesigns/TickerIO#2]
Hi,

I think there is a shell in the app description: 
- TickerIO is a free, minimalistic app to quickly display local and Zulu (military) time, as well as the julian date.  This version offers a light and dark theme.

According to my knowledge the military timezone is Alpha (UTC+1) but maybe I'm wrong for a reason or another...

**Comment by drewstephensdesigns** [comment]
Hi! Thanks for the feedback.  UTC is like a starting point by which to convert time across the world. It is the same time zone as GMT (Greenwich Mean Time). UTC is also referred to as Zero Meridian Time. The military calls the UTC time zone, Zulu Time, referring to the letter which represents it “Z” and the army’s call sign for it (Zulu). The UTC offsets, represent the difference in time from 0.

Drew Stephens
Sent via the Samsung Galaxy S9+
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MockingMagician** [comment]
> The military calls the UTC time zone, Zulu Time

Yes it is the name used by military for UTC but it is not the military time zone whom is ALPHA. Why just you didn't say UTC ? I think that is more universal and really speak to everyone (more than Zulu time)

**Comment by drewstephensdesigns** [comment]
Because what we use in the military and what I use in the app is the true Zulu time. I wrote this app while deployed and targeted military more than civilian use. It is correct in use and fact.

Drew Stephens
Sent via the Samsung Galaxy S9+
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MockingMagician** [comment]
Looks fair :wink: thank you for these details.

I close
